version: 0.0
os: linux
files:
  - source: /
    destination: /var/app
    overwrite: true
hooks:
  # ApplicationStop:
  #   - location: scripts/stop.sh
  #     timeout: 60
  #     runas: root

  BeforeInstall:
    - location: scripts/delete.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: root

file_exists_behavior: OVERWRITE
