# this docker compose file will runn each Dockerfile from each service on a diffrerent container and port
# to run this file use the command: docker-compose up -d --build
# to stop the containers use: docker-compose down
# to delete the images use: docker rmi -f $(docker images -a -q)

version: '3'
services:
  service1: #this is the name of the service
    image: dockertest/service_a #this is the name of the image created by the Dockerfile
    build: ./service_a #this is the name of the folder where the Dockerfile is to rebuild it automatically to keep it updated
    ports:
      - '8081:3000'
    restart: always
  service2: #this is the name of the service
    image: dockertest/service_b #this is the name of the image created by the Dockerfile
    build: ./service_b #this is the name of the folder where the Dockerfile is to rebuild it automatically to keep it updated
    ports:
      - '8082:3000'
    restart: always
